export default {
  MENU_ON: 'MENU_ON',
  MENU_OFF: 'MENU_OFF',
  TOGGLE_MENU: 'TOGGLE_MENU',
  CHANGE_SECTION: 'CHANGE_SECTION',
  SET_CURRENT_SECTION: 'SET_CURRENT_SECTION',
  PULL_FROM_INSTAGRAM: 'PULL_FROM_INSTAGRAM',
  REQUEST_INSTAGRAM_ACCESS_TOKEN: "REQUEST_INSTAGRAM_ACCESS_TOKEN",
  SET_INSTAGRAM_PROFILE: "SET_INSTAGRAM_PROFILE",
  SET_INSTAGRAM_RECENT_MEDIA: "SET_INSTAGRAM_RECENT_MEDIA"
}
